Adaptation to scilpy
scilus/bst_flow pull request #2
Opened 2020-07-02 22:40 UTC by frheault

Adapted to the recent modif in scilpy

2020-09-10 16:08 UTC, alexjoa commented
@frheault can you send some data to test on please.

2020-09-10 17:40 UTC, frheault reviewed
-

2020-09-11 13:52 UTC, alexjoa approved these changes
Code reviewed.

2020-09-11 13:52 UTC, alexjoa commented on USAGE
> +--sh_basis                                 SH basis of the input FOD ($sh_basis)
Extra tab?

2020-10-02 13:44 UTC, GuillaumeTh requested changes
Crash with one of my dataset. 
```   
 File "/usr/local/lib/python3.7/dist-packages/scilpy-0.2.dev0-py3.7-linux-x86_64.egg/scilpy/io/image.py", line 71, in get_data_as_mask
      'with a mask'.format(basename, curr_type))
  OSError: The image S1__AF_R_m_tracking_mask.nii.gz cannot be loaded as mask because its type <class 'numpy.float32'> is not compatible with a mask
```

2020-10-02 14:57 UTC, GuillaumeTh approved these changes
Thanks for the fix

2020-10-17 12:12 UTC, mdesco approved these changes
Again, aside from my comestic suggestions. This works and was tested with and without the singularity tractoflow-scilpy-rc2

2020-10-17 12:12 UTC, mdesco commented on USAGE
> +--sh_basis                              SH basis of the input FOD ($sh_basis)
Please specify the options for the user "descoteaux07" or "tournier07" for example
Otherwise, the user does not know what to provide

2020-10-17 12:12 UTC, mdesco commented on main.nf
> +    "and --atlas_directory all are mandatory."
Can we put the atlas used in your paper on zenodo as well please?
With the link here and the proper folder structure?
Thanks

2020-10-23 14:46 UTC, GuillaumeTh commented
I do a test and merge if everything is fine

2020-10-23 15:22 UTC, merged